create table HOTEL
(
    ID          INTEGER default (NEXT VALUE FOR TRAVELAGENCY.SYSTEM_SEQUENCE_E7D6C7BD_AE6B_45C2_A564_785C221735EE) auto_increment,
    NAMEHOTEL   VARCHAR(20) not null
        constraint HOTEL_NAMEHOTEL_UINDEX
            unique,
    RATINGSTARS INTEGER     not null,
    constraint HOTEL_PK
        primary key (ID)
);

INSERT INTO TRAVELAGENCY.HOTEL (ID, NAMEHOTEL, RATINGSTARS) VALUES (1, 'Beach Resort', 3);
INSERT INTO TRAVELAGENCY.HOTEL (ID, NAMEHOTEL, RATINGSTARS) VALUES (2, 'Blue water', 4);
INSERT INTO TRAVELAGENCY.HOTEL (ID, NAMEHOTEL, RATINGSTARS) VALUES (3, 'Old human resort', 5);