create table USER
(
    ID       INTEGER default (NEXT VALUE FOR TRAVELAGENCY.SYSTEM_SEQUENCE_AA92808C_3ABB_49CA_B1A0_54070510E2EB) auto_increment,
    NAMEUSER VARCHAR(20) not null,
    constraint USER_PK
        primary key (ID)
);

INSERT INTO TRAVELAGENCY.USER (ID, NAMEUSER) VALUES (1, 'Pavel');
INSERT INTO TRAVELAGENCY.USER (ID, NAMEUSER) VALUES (2, 'Sergey');
INSERT INTO TRAVELAGENCY.USER (ID, NAMEUSER) VALUES (3, 'Olga');