create table COUNTRY
(
    ID          INTEGER default (NEXT VALUE FOR TRAVELAGENCY.SYSTEM_SEQUENCE_CC06B55B_3BE6_4269_9A07_C196F61A88E2) auto_increment,
    NAMECOUNTRY VARCHAR(20) not null
        constraint COUNTRY_NAMECOUNTRYINT_UINDEX
            unique,
    constraint COUNTRY_PK
        primary key (ID)
);

INSERT INTO TRAVELAGENCY.COUNTRY (ID, NAMECOUNTRY) VALUES (1, 'Belarus');
INSERT INTO TRAVELAGENCY.COUNTRY (ID, NAMECOUNTRY) VALUES (2, 'Russia');
INSERT INTO TRAVELAGENCY.COUNTRY (ID, NAMECOUNTRY) VALUES (3, 'Ukraine');